---
colors:
  primary:
    background: '0x002b36'
    foreground: '0x839496'
  normal:
    black: '0x073642'
    red: '0xdc322f'
    green: '0x859900'
    yellow: '0xb58900'
    blue: '0x268bd2'
    magenta: '0xd33682'
    cyan: '0x2aa198'
    white: '0xeee8d5'
  bright:
    black: '0x002b36'
    red: '0xcb4b16'
    green: '0x586e75'
    yellow: '0x657b83'
    blue: '0x839496'
    magenta: '0x6c71c4'
    cyan: '0x93a1a1'
    white: '0xfdf6e3'
font:
  normal:
    family: DejaVu Sans Mono
    style: Regular
  bold:
    family: DejaVu Sans Mono
    style: Bold
  italic:
    family: DejaVu Sans Mono
    style: Italic
  bold_italic:
    family: DejaVu Sans Mono
    style: Bold Italic
  size: 9.0
mouse:
  hide_when_typing: true
scrolling:
  history: 0
window:
  decorations: none
  startup_mode: Fullscreen
