---
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
rules:
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
  indent:
    - 2
    - 2
  no-unused-vars:
    - 2
    - {argsIgnorePattern: ^_}
  no-extra-parens:
    - 2
env:
  browser: true
  jquery: true
extends: eslint:recommended
