- name: Install packages
  community.general.pacman:
    name:
      - ansible
      - aws-cli
      - less
      - p7zip
      - pv
      - ripgrep
      - rsync
      - sshpass
      - unzip
      - usbutils
      - which
      - zip
    update_cache: true
